version: '2'
services:
    monolith-app:
        image: monolith
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://monolith-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=monolith
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    monolith-mongodb:
        extends:
            file: mongodb.yml
            service: monolith-mongodb
